### ISSUE TITLE
feature/notion

### ISSUE THREAD

**Issue by un-null** [un-null/medium#1]
# Todo
- [ ] setup notion
- [ ] setup notino color
- [ ] fetch notion data
- [ ] display notion data

# Memo
- embed (image, video, spotify)
- link card (bookmark)
